apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    stream_over_http_enabled: true
    server:
      http_listen_port: 3100
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
    ingester:
      trace_idle_period: 30s
      max_block_bytes: 1048576
    querier:
      frontend_worker:
        frontend_address: 127.0.0.1:9095
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
    metrics_generator:
      storage:
        path: /var/tempo/metrics
    compactor:
      compaction:
        block_retention: 48h
