apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    app: loki
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3300
      grpc_listen_port: 9096
      log_level: debug
      grpc_server_max_concurrent_streams: 1000
    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    chunk_store_config: {}
    compactor:
      working_directory: /tmp/loki/retention
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: filesystem
    limits_config:
      retention_period: 48h
    ruler:
      alertmanager_url: http://localhost:9093
    frontend:
      encoding: protobuf
